/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "config.h"
void configuart(void);
void usart_sendchar(char c);
void usart_sendstring(char *string);
uint8_t usart_getchar();
int main(void)
{
	config();
	configuart();
    /* Loop forever */
	while(1){


	uint8_t temp=	usart_getchar();
	delay_ms(1000);
	GPIOC->ODR &=~ GPIO_ODR_ODR13;

	usart_sendchar(temp);
	delay_ms(1000);
	GPIOC->ODR |= GPIO_ODR_ODR13;

	usart_sendchar(temp);
	delay_ms(1000);




		}
}

void configuart(void){
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;
	RCC-> APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_AFIOEN;

	GPIOA->CRH &=~ GPIO_CRH_CNF9;
	GPIOA->CRH |= GPIO_CRH_CNF9_1;
	GPIOA->CRH |= GPIO_CRH_MODE9_0;
	GPIOA->CRH |= GPIO_CRH_MODE9_1;

	GPIOA->CRH &=~ GPIO_CRH_CNF10;
	GPIOA->CRH |= GPIO_CRH_CNF10_1;
	GPIOA->CRH |= GPIO_CRH_MODE10_0;
	GPIOA->CRH |= GPIO_CRH_MODE10_1;



	USART1->CR1 |= USART_CR1_UE;
	USART1->CR1 &=~ USART_CR1_M;

	USART1->BRR |= (5<<0) | (208<<4);// baud 2400 , clock 8mhz

	USART1->CR1 |= USART_CR1_RE;
	USART1->CR1 |= USART_CR1_TE;

}

void usart_sendchar(char c){

	USART1->DR =c;
	while(!(USART1->SR & USART_SR_TC));

}
void usart_sendstring(char *string){


	while(*string){
		usart_sendchar(*string++);

	}

}
uint8_t usart_getchar(void){

	uint8_t temp;
	while(!(USART1->SR & USART_SR_RXNE));
	temp=USART1->DR;
	return temp;

}
